const connectDatabase = require('../src/config/database');
const Property = require('../src/models/Property');

const seedProperties = [
	{
		name: '1965 Calais Dr Boat Slip',
		slug: '1965-calais-dr-miami-beach-boat-slip',
		location: 'Miami Beach, FL',
		addressLine1: '1965 Calais Dr',
		city: 'Miami Beach',
		state: 'FL',
		country: 'USA',
		postalCode: '33141',
		description:
			'Secure residential boat slip located in a quiet Miami Beach neighborhood. Ideal for small vessels looking for quick and easy access to Biscayne Bay. This is a dry/basic slip with no power or water hookups, perfect for park-and-go convenience.',
		investorHeadline: 'Affordable Entry Into Miami Waterfront Assets',
		investorSummary:
			'This listing offers investors exposure to Miami Beach waterfront infrastructure at a low entry price. With steady demand for private docking spaces and minimal maintenance overhead, this boat slip represents a low-risk, cash-flow opportunity.',
		highlights: [
			'Direct access to Biscayne Bay',
			'Quiet residential location',
			'Low maintenance asset',
			'Ideal for small boats and pontoons',
			'Affordable investment tier',
		],
		trustBadges: ['Verified Location', 'Low Risk Asset', 'Income Generating', 'Waterfront Property'],
		tags: ['marine', 'boat-slip', 'miami-beach', 'waterfront'],
		market: 'Miami Beach',
		propertyType: 'boat_slip',
		listingType: 'Boat Slip',
		beds: 0,
		baths: 1,
		sqft: 0,
		yearBuilt: 0,
		images: [
			'https://images.unsplash.com/photo-1500375592092-40eb2168fd21?auto=format&fit=crop&w=1600&q=80',
			'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1600&q=80',
			'https://images.unsplash.com/photo-1518837695005-2083093ee35b?auto=format&fit=crop&w=1600&q=80',
		],
		coverImage: 'https://images.unsplash.com/photo-1500375592092-40eb2168fd21?auto=format&fit=crop&w=1600&q=80',
		sourceName: 'Zillow',
		sourceUrl: 'https://www.zillow.com/',
		sourceListingId: '1965-calais-dr-miami',
		totalValue: 12000,
		acquisitionCost: 9000,
		targetRaiseAmount: 6000,
		totalSlots: 12,
		fundedSlots: 0,
		fundedPercentage: 0,
		totalInvestors: 0,
		expectedAnnualYield: 24,
		slotBasePriceMonthly: 500,
		minimumInvestmentMonths: 3,
		maximumInvestmentMonths: 12,
		allowedDurations: [3, 6, 12],
		payoutCurrency: 'USDT',
		currentDailyPayoutAmount: 8,
		projectedMonthlyPayoutAmount: 240,
		projectedAnnualPayoutAmount: 2880,
		occupancyScore: 82,
		demandScore: 78,
		targetOccupancyRate: 70,
		riskLevel: 'low',
		verified: true,
		availabilityWindowLabel: 'Available Now',
		investmentStatus: 'active',
		status: 'active',
		isPublished: true,
	},
	{
		name: 'The Watts at Hampton Cove',
		slug: 'the-watts-hampton-cove',
		location: 'Huntsville, AL',
		addressLine1: '7235 Highway 431 S, Owens Cross Roads, AL 35763',
		city: 'Huntsville',
		state: 'AL',
		country: 'United States',
		postalCode: '35763',
		description: 'Modern rental asset in the Huntsville growth corridor with investor-friendly daily payout structure.',
		investorHeadline: 'Modern Huntsville rental asset with daily earning potential',
		investorSummary: 'Reserve a rental income period and receive daily profits while maintaining flexible withdrawals.',
		highlights: [
			'Reserve rental income access with 3 to 15 month durations',
			'Daily profit track with admin-managed payout approvals',
			'Huntsville growth corridor demand and strong occupancy support',
		],
		trustBadges: ['Featured product', 'Verified property', 'Operator managed', 'Flexible withdrawal posture'],
		tags: ['featured', 'verified', 'huntsville', 'short-term-rental'],
		market: 'Huntsville',
		propertyType: 'apartment_building',
		listingType: 'Apartment Building',
		marketType: 'Short-Term Rental',
		beds: 1,
		baths: 1,
		sqft: 871,
		yearBuilt: 2022,
		amenities: ['Resort-style saltwater pool', 'Fitness studio', 'Washer and dryer in all homes', 'Smart keyless entry'],
		images: [
			'https://photos.zillowstatic.com/fp/ffa7a49407b03ec4a31897b4f26e605f-sr_960_640.webp',
			'https://photos.zillowstatic.com/fp/b1351592fcd307f4193b745f086e4eb7-sr_960_640.webp',
		],
		coverImage: 'https://photos.zillowstatic.com/fp/ffa7a49407b03ec4a31897b4f26e605f-sr_960_640.webp',
		sourceName: 'Zillow',
		sourceUrl: 'https://www.zillow.com/apartments/huntsville-al/the-watts/CqC3KZ/',
		sourceListingId: 'CqC3KZ',
		totalValue: 325000,
		availableUnits: 0,
		totalSlots: 7,
		fundedSlots: 5,
		fundedPercentage: 68,
		totalInvestors: 12,
		expectedAnnualYield: 0,
		slotBasePriceMonthly: 1200,
		minimumInvestmentMonths: 3,
		maximumInvestmentMonths: 15,
		allowedDurations: [3, 6, 9, 12, 15],
		payoutCurrency: 'USDT',
		currentDailyPayoutAmount: 18,
		projectedMonthlyPayoutAmount: 540,
		projectedAnnualPayoutAmount: 6480,
		estimatedMonthlyProfit: 540,
		estimatedQuarterlyProfit: 1620,
		estimatedYearlyProfit: 6480,
		occupancyScore: 91,
		demandScore: 87,
		riskLevel: 'low',
		featured: true,
		verified: true,
		profitsWithdrawAnytime: true,
		capitalWithdrawAnytime: true,
		adminWithdrawalApproval: true,
		operatorManaged: true,
		activeReservations: 7,
		recentPayoutsCount: 84,
		nextAvailableStartDate: new Date('2026-04-05'),
		blockedDates: [
			{ startDate: new Date('2026-04-10'), endDate: new Date('2026-07-10'), reason: 'Reserved slot window' },
			{ startDate: new Date('2026-08-01'), endDate: new Date('2026-11-01'), reason: 'Reserved slot window' },
		],
		payoutHistory: [{ amount: 18, currency: 'USDT', effectiveDate: new Date('2026-03-01') }],
		payoutMode: 'manual_daily',
		payoutChangedAt: new Date('2026-03-01'),
		availabilityWindowLabel: 'Next opening starts on 2026-04-05',
		investmentStatus: 'active',
		status: 'active',
		isPublished: true,
	},
	{
		name: 'Brickell Skyline Suites',
		slug: 'brickell-skyline-suites',
		location: 'Brickell, Miami, FL',
		addressLine1: '1010 Brickell Ave',
		city: 'Miami',
		state: 'FL',
		country: 'United States',
		postalCode: '33131',
		description:
			'Premium short-stay apartment positioned for business travel, weekend city breaks, and extended relocation demand in central Miami.',
		investorHeadline: 'Downtown Miami cashflow inventory with year-round traveler demand.',
		investorSummary:
			'Built for investors who want fast-moving urban occupancy, premium ADR potential, and a property story that is easy to sell on the front end.',
		highlights: ['Walkable to Brickell financial district', 'Business and leisure demand mix', 'Operator-ready furnished format'],
		trustBadges: ['Verified payout history', 'Prime urban demand corridor', 'Admin-managed daily distributions'],
		tags: ['urban-demand', 'premium-adr', 'business-travel'],
		market: 'Miami',
		propertyType: 'serviced_apartment',
		beds: 2,
		baths: 2,
		sqft: 1180,
		images: [
			'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1600&q=80',
			'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1600&q=80',
		],
		coverImage: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1600&q=80',
		sourceName: 'InvestAir Internal Deal Desk',
		sourceUrl: 'https://investair.example/properties/brickell-skyline-suites',
		sourceListingId: 'IA-FL-001',
		totalValue: 385000,
		acquisitionCost: 332000,
		targetRaiseAmount: 48000,
		totalSlots: 12,
		fundedSlots: 7,
		totalInvestors: 7,
		expectedAnnualYield: 18.4,
		slotBasePriceMonthly: 1800,
		minimumInvestmentMonths: 2,
		allowedDurations: [2, 3, 6, 12],
		payoutCurrency: 'USDT',
		currentDailyPayoutAmount: 95,
		projectedMonthlyPayoutAmount: 2850,
		projectedAnnualPayoutAmount: 34200,
		occupancyScore: 91,
		demandScore: 94,
		targetOccupancyRate: 82,
		riskLevel: 'low',
		payoutHistory: [{ amount: 95, currency: 'USDT', effectiveDate: new Date('2026-03-01') }],
		payoutMode: 'manual_daily',
		payoutChangedAt: new Date('2026-03-01'),
		availabilityWindowLabel: 'Open for April and May reservations',
		status: 'active',
	},
	{
		name: 'Downtown Detroit Host Loft',
		slug: 'downtown-detroit-host-loft',
		location: 'Downtown Detroit, MI',
		addressLine1: '1529 Broadway St',
		city: 'Detroit',
		state: 'MI',
		country: 'United States',
		postalCode: '48226',
		description:
			'Modern loft configured for event-driven and corporate stay demand with quick turn cleaning operations and strong occupancy resilience.',
		investorHeadline: 'Event-calendar driven occupancy with strong Midwest entry pricing.',
		investorSummary:
			'Lower entry price, stable demand, and a clean admin payout story make this a strong mid-market slot product for newer investors.',
		highlights: ['Near convention and sports venues', 'Affordable slot entry point', 'Short turn servicing workflow already mapped'],
		trustBadges: ['Mid-market pricing moat', 'Recurring event demand', 'Transparent slot durations'],
		tags: ['event-driven', 'midwest', 'entry-ticket'],
		market: 'Detroit',
		propertyType: 'urban_loft',
		beds: 1,
		baths: 1,
		sqft: 860,
		images: [
			'https://images.unsplash.com/photo-1494526585095-c41746248156?auto=format&fit=crop&w=1600&q=80',
			'https://images.unsplash.com/photo-1484154218962-a197022b5858?auto=format&fit=crop&w=1600&q=80',
		],
		coverImage: 'https://images.unsplash.com/photo-1494526585095-c41746248156?auto=format&fit=crop&w=1600&q=80',
		sourceName: 'InvestAir Internal Deal Desk',
		sourceUrl: 'https://investair.example/properties/downtown-detroit-host-loft',
		sourceListingId: 'IA-MI-002',
		totalValue: 228000,
		acquisitionCost: 191000,
		targetRaiseAmount: 26000,
		totalSlots: 10,
		fundedSlots: 4,
		totalInvestors: 4,
		expectedAnnualYield: 15.2,
		slotBasePriceMonthly: 1100,
		minimumInvestmentMonths: 2,
		allowedDurations: [2, 3, 6, 9, 12],
		payoutCurrency: 'USDT',
		currentDailyPayoutAmount: 56,
		projectedMonthlyPayoutAmount: 1680,
		projectedAnnualPayoutAmount: 20160,
		occupancyScore: 78,
		demandScore: 81,
		targetOccupancyRate: 74,
		riskLevel: 'moderate',
		payoutHistory: [{ amount: 56, currency: 'USDT', effectiveDate: new Date('2026-03-01') }],
		payoutMode: 'manual_daily',
		payoutChangedAt: new Date('2026-03-01'),
		availabilityWindowLabel: 'Open for next immediate start window',
		status: 'active',
	},
	{
		name: 'Scottsdale Desert Retreat',
		slug: 'scottsdale-desert-retreat',
		location: 'Scottsdale, AZ',
		addressLine1: '7125 E Camelback Rd',
		city: 'Scottsdale',
		state: 'AZ',
		country: 'United States',
		postalCode: '85251',
		description:
			'Lifestyle-oriented home targeting premium leisure traffic, golf weekends, and group bookings with above-market nightly positioning.',
		investorHeadline: 'Higher-ticket leisure inventory with premium nightly upside.',
		investorSummary:
			'This product is designed for investors who want stronger per-day payout potential and can accept a slightly more cyclical booking curve.',
		highlights: ['Premium leisure market', 'Strong seasonal ADR upside', 'Group booking positioning'],
		trustBadges: ['Premium traveler profile', 'Above-market ADR strategy', 'Flexible duration ladder'],
		tags: ['premium-leisure', 'seasonal-upside', 'group-bookings'],
		market: 'Scottsdale',
		propertyType: 'villa',
		beds: 3,
		baths: 2,
		sqft: 1640,
		images: [
			'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1600&q=80',
			'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1600&q=80',
		],
		coverImage: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1600&q=80',
		sourceName: 'InvestAir Internal Deal Desk',
		sourceUrl: 'https://investair.example/properties/scottsdale-desert-retreat',
		sourceListingId: 'IA-AZ-003',
		totalValue: 462000,
		acquisitionCost: 401000,
		targetRaiseAmount: 65000,
		totalSlots: 14,
		fundedSlots: 11,
		totalInvestors: 10,
		expectedAnnualYield: 20.1,
		slotBasePriceMonthly: 2400,
		minimumInvestmentMonths: 3,
		allowedDurations: [3, 6, 12, 18],
		payoutCurrency: 'USDT',
		currentDailyPayoutAmount: 128,
		projectedMonthlyPayoutAmount: 3840,
		projectedAnnualPayoutAmount: 46080,
		occupancyScore: 84,
		demandScore: 89,
		targetOccupancyRate: 76,
		riskLevel: 'moderate',
		payoutHistory: [{ amount: 128, currency: 'USDT', effectiveDate: new Date('2026-03-01') }],
		payoutMode: 'manual_daily',
		payoutChangedAt: new Date('2026-03-01'),
		availabilityWindowLabel: 'Limited summer inventory remaining',
		status: 'active',
	},
];

async function main() {
	await connectDatabase();

	for (const property of seedProperties) {
		await Property.findOneAndUpdate({ slug: property.slug }, property, {
			upsert: true,
			new: true,
			setDefaultsOnInsert: true,
		});
	}

	console.log(`Seeded ${seedProperties.length} investment properties`);
}

if (require.main === module) {
	main()
		.catch((error) => {
			console.error('Failed to seed properties', error);
			process.exitCode = 1;
		})
		.finally(async () => {
			const mongoose = require('mongoose');
			await mongoose.connection.close();
		});
}

module.exports = {
	seedProperties,
	main,
};
